### ISSUE TITLE
Migration creation

### ISSUE THREAD

**Issue by Gas9220** [Gas9220/laravel-steam-collection#1]
Creare una migration di una tabella che abbia i seguenti campi:
Nome db: steam_db
|---|---|---|---|---|
|  Dato  |  Tipo di dato
|  title  |  string  | 
|  publisher  | string(40) |
|  publication_year | date |
|  developers | string(40) |
|  platform | string |
|  description | text |
|  pegi | tinyinteger |
|  genre | string |
|  rating | float(3,1) |
| thumbnail | text |
| min_requirements | text |

**Comment by Gas9220** [comment]
A seguito di un analisi approfondita è stato deciso di rimuovere i requisiti minimi e aggiungere il campo early_access | boolean default(0)

**Comment by CosimoPetrarca** [comment]
ok capo sarà eseguito
